### PR TITLE
fixed iOS 8.3 method conflict

### PR DESCRIPTION
**Pull request by NSCabezon**

### CODE REVIEW

**Comment by cwalcott** [comment]
Hi, did you have to enable a particular warning or include a particular framework in order for this error to show up? I'm hesitant to rename a method like this which could introduce breaking changes into people's code.

**Comment by NSCabezon** [comment]
I see your point, and no, I just built the project with iOS 8.3 base SDK. Maybe is not the best way to solve it but that's what I came up with :)

captura de pantalla 2015-04-09 a las 16 56 33

**Comment by cwalcott** [comment]
Hmm, I wish I knew why building the project doesn't have that behavior for me. Are you building ZXingObjC or a project that uses it?

**Comment by NSCabezon** [comment]
I'm using it on a project along with many libraries

**Comment by ldamman** [comment]
I started hitting this error after upgrading to Xcode 6.3 / Swift 1.2.  I was able to silence it without renaming the method by explicitly using the class name instead of self in ZXParsedResult.m...

```-  return [[self alloc] initWithType:type];
+  return [[ZXParsedResult alloc] initWithType:type];
```

**Comment by cwalcott** [comment]
@ldamman That particular change was made in d8c80a298e1ca9483b69c5df1c6d307e69ec8c6b. Are you seeing any issues with the calls to `[super initWithType:]`?

**Comment by gimenete** [comment]
JFYI: I saw this issue with an older version of the library. With the latest version it works.

**Pull request closed without merging**
